### ISSUE TITLE
Docker Compose File Example

### ISSUE THREAD

**Issue by raindancer2204** [eea/eea.docker.rsync#11]
Hello,

i think this project is really great.

I've also read the documentation.

Would it be possible to show the examples as Docker Compose.yaml in the documentation?

It would really simplify things.

Thank you and keep it up

**Comment by cat0x1f** [comment]
This is my docker compose sample of rsync to my nas (via nfs) 

```yaml
version: "3.3"
services:
  rsync:
    container_name: rsync_client
    volumes:
      - ssh-key:/root/.ssh
      - remote-nfs:/remote
      - /docker:/local
    environment:
      - CRON_TASK_1=0 0 * * * rsync -rva --delete /local/ /remote/
    image: eeacms/rsync
    command: client
    restart: unless-stopped
    network_mode: host
volumes:
  ssh-key: null
  remote-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.8.2.10,nolock,soft,rw,vers=4
      device: :/mnt/catpool/backup/HomeDocker
networks: {}
```
